# # https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives
# [build-system]
# # Chose setuptools just in case I add any C/C++ in the future.
# # It's not like I'm afraid of difficult environmental
# # configurations.
# requires = ['setuptools >= 77.0.3']
# build-backend = 'setuptools.build_meta'

# [project]
# name = 'LegalFoodDefinitionsUS_kayla-kubicke'
# version = '1.0.0'
# authors = [
#   { name='kayla-kubicke', email='161649341+kayla-kubicke@users.noreply.github.com' },
# ]
# maintainers = [
#   { name='kayla-kubicke', email='161649341+kayla-kubicke@users.noreply.github.com' },
# ]
# description = 'A search tool to navigate food terms regulated by US law.'
# readme = 'README.md'
# requires-python = '>=3.9'
# classifiers = [
#     'Programming Language :: Python :: 3',
#     'Operating System :: OS Independent',
# ]
# license = 'MIT'
# license-files = ['LICEN[CS]E*']
# [project]
# dependencies = [
# 	'requests >= 2.33.1'
# ]

# [project.urls]
# Homepage = 'https://github.com/kayla-kubicke/LegalFoodDefinitionsUS'
# Issues = 'https://github.com/kayla-kubicke/LegalFoodDefinitionsUS/issues'